/*
 * The setup command's conversation. setup.h is the specification and
 * packages/backend/src/setup/askForSetup.ts is the reference this is held to.
 *
 * Legacy reads COMMUNITY_NAME and COMMUNITY_DESCRIPTION out of the environment at every start.
 * gradido2 asks once and writes a row, because these are not settings -- they are the identity
 * of a community, written once and then referred to. An environment variable that has silently
 * drifted from the row it created is a confusion that does not need to exist, and the key pair
 * that goes with the row could never have come from an env file anyway.
 *
 * **Only what a person knows is asked.** The uuid, the ed25519 key pair and the timestamps are
 * generated by the interaction; a prompt for any of them would be a way to get them wrong.
 *
 * Each answer is checked against the same rules an admin route will later check a rename
 * against, and a rejected answer is asked again rather than ending the setup -- somebody is
 * standing at the terminal, and losing eleven correct answers because the twelfth had a typo
 * would be gratuitous.
 *
 * **The database is asked first**, because it is the one answer that depends on this machine
 * rather than on the person at it: SQLite needs nothing, PostgreSQL needs a server that is
 * already running. So the conversation looks before it asks -- see postgres_probe.h -- and a
 * database that is configured already is offered as it stands, so that a rerun of setup to
 * change the relay does not end up somewhere else.
 *
 * The question after it decides how many of the others are asked. A development installation is
 * a known thing -- this machine and the MailDev container of the repository's docker-compose.yml
 * -- so it is proposed as a block and taken with one Enter.
 */
#include "setup.h"

#include <sodium.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "field_rules.h"
#include "postgres_probe.h"
#include "service_core/secret.h"
#include "prompt.h"
#include "service_core/email/transport.h"

/** What the development proposal is, and what `.env.dist` calls the same fields. */
#define DEVELOPMENT_COMMUNITY_NAME "Gradido Dev Community"
#define DEVELOPMENT_COMMUNITY_URL "http://localhost"
/** The relay of the repository's docker-compose.yml -- MAILDEV_SMTP_PORT, one above maildev's
 *  own 1025 so that a checkout of legacy can be up at the same time. */
#define MAILDEV_SMTP_PORT "1026"
/** And the web interface that shows what arrived -- MAILDEV_WEB_PORT. */
#define MAILDEV_WEB_PORT "1081"

/* The database defaults of packages/backend-core/src/database/schema.ts, which
 * service-core/src/db.c mirrors for a start. Mirrored again rather than read through
 * sc_db_config_load: that one refuses a configuration a setup is here to repair, and says so as a
 * fatal log line. What a question proposes and what a start would use must not differ. */
#define DEFAULT_DB_FILE "./gradido_community.sqlite"
#define DEFAULT_DB_HOST "/var/run/postgresql"
#define DEFAULT_DB_PORT "5432"
#define DEFAULT_DB_DATABASE "gradido_community"
#define DEFAULT_DB_USER "gradido"

/** The password docker-compose.yml starts its PostgreSQL with when the environment names none --
 *  ${DB_PASSWORD:-gradido} there. User and database have the same defaults as the configuration,
 *  so they need no constant of their own. */
#define DOCKER_COMPOSE_POSTGRES_PASSWORD "gradido"

/** What the start refuses an empty password over TCP in production with --
 *  DATABASE_PASSWORD_MESSAGE on the reference path. */
#define DATABASE_PASSWORD_MESSAGE                                                                  \
    "an empty database password is not acceptable in production over TCP; it is correct over a "   \
    "Unix socket, which is what a DB_HOST beginning with \"/\" selects"

/** The rules of packages/shared/src/schemas/community.ts and of the mail configuration, in the
 *  order the pipes that define them apply. */
typedef enum answer_kind {
    ANSWER_NAME,
    ANSWER_DESCRIPTION,
    ANSWER_URL,
    ANSWER_REQUIRED,
    ANSWER_OPTIONAL,
    ANSWER_PORT,
    ANSWER_EMAIL
} answer_kind;

/**
 * Whether @p text is a URL by the rule `v.url()` applies, which is whether `new URL(text)`
 * parses.
 *
 * Approximated rather than reproduced: the WHATWG parser is a specification, not a predicate,
 * and carrying it here to accept `mailto:x` -- which that rule does accept -- would buy nothing
 * this prompt wants. What is checked is a scheme, a colon, and, for the schemes that must have
 * one, a host. The difference is a value the reference path would take and this one asks again
 * about, on an interactive prompt, and it is written down here rather than left to be
 * discovered.
 */
static int is_url(const char *text, size_t length)
{
    static const char *const kSpecial[] = {"http", "https", "ws", "wss", "ftp"};
    size_t scheme = 0;
    size_t host = 0;
    size_t i;

    if (length == 0)
        return 0;
    if (!((text[0] >= 'A' && text[0] <= 'Z') || (text[0] >= 'a' && text[0] <= 'z')))
        return 0;
    while (scheme < length && text[scheme] != ':') {
        char c = text[scheme];
        if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') ||
              c == '+' || c == '-' || c == '.'))
            return 0;
        ++scheme;
    }
    if (scheme == length || scheme == 0)
        return 0;
    /* Something has to follow the colon; `http:` on its own is not a URL to anybody. */
    if (scheme + 1 == length)
        return 0;

    for (i = 0; i != sizeof(kSpecial) / sizeof(kSpecial[0]); ++i) {
        size_t len = strlen(kSpecial[i]);
        size_t start;

        if (len != scheme)
            continue;
        {
            size_t c;
            for (c = 0; c != len; ++c) {
                char left = text[c];
                if (left >= 'A' && left <= 'Z')
                    left = (char)(left - 'A' + 'a');
                if (left != kSpecial[i][c])
                    break;
            }
            if (c != len)
                continue;
        }
        /* A special scheme needs a host, and the "//" before it is optional only in the sense
         * that the parser inserts it -- either way there has to be something to connect to. */
        start = scheme + 1;
        while (start < length && text[start] == '/')
            ++start;
        while (start + host < length && text[start + host] != '/' && text[start + host] != '?' &&
               text[start + host] != '#')
            ++host;
        return host != 0;
    }
    return 1;
}

/** The message the rule for @p kind refuses @p text with, or NULL when it takes it. */
static const char *refusal_for(answer_kind kind, const char *text)
{
    size_t length = strlen(text);
    size_t units = bk_utf16_length(text, length);

    switch (kind) {
    case ANSWER_NAME:
        /* nonEmpty before maxLength, which is the order communityNameSchema pipes them. */
        if (length == 0)
            return "This field is required";
        return units > 40 ? "This name is too long" : NULL;
    case ANSWER_DESCRIPTION:
        return units > 255 ? "This description is too long" : NULL;
    case ANSWER_URL:
        if (length == 0)
            return "This field is required";
        if (units > 255)
            return "This URL is too long";
        return is_url(text, length) ? NULL : "Please enter a valid URL, including https://";
    case ANSWER_PORT: {
        char *end;
        unsigned long parsed = strtoul(text, &end, 10);

        if (length == 0 || *end != '\0' || parsed == 0 || parsed > 65535)
            return "This must be a port between 1 and 65535";
        return NULL;
    }
    case ANSWER_EMAIL:
        if (length == 0)
            return "This field is required";
        if (units > 255)
            return "This email address is too long";
        return bk_is_email(text, length) ? NULL : "Please enter a valid email address";
    case ANSWER_REQUIRED:
        return length == 0 ? "This field is required" : NULL;
    case ANSWER_OPTIONAL:
    default:
        return NULL;
    }
}

/**
 * Asks until the answer passes the rule, and copies it into @p out.
 *
 * The rule before the buffer, and that order is the whole reason this is not just
 * bk_prompt_text: a name of forty-five characters is refused with "This name is too long",
 * which is what the reference path says and what the admin frontend will say about the same
 * field later. Only a value the rule takes and the column cannot hold falls through to the
 * second message.
 *
 * Answers 0 at the end of input -- a terminal that went away mid-setup, which is not an answer.
 */
static int ask(const char *label, const char *fallback, answer_kind kind, char *out,
               size_t out_size)
{
    char answer[BK_ANSWER_MAX];

    for (;;) {
        const char *refusal;
        size_t begin = 0;
        size_t trimmed = 0;

        if (!bk_prompt_text(label, fallback, answer, sizeof(answer)))
            return 0;
        /* Trimmed the way JavaScript trims, which removes rather more than the ASCII
         * whitespace the prompt itself took off -- U+00A0 and U+FEFF are in that set, and a
         * value pasted out of a web page carries them. */
        bk_trim(answer, strlen(answer), &begin, &trimmed);
        memmove(answer, answer + begin, trimmed);
        answer[trimmed] = '\0';

        refusal = refusal_for(kind, answer);
        if (refusal == NULL && trimmed + 1 > out_size)
            refusal = "This value is too long";
        if (refusal == NULL) {
            memcpy(out, answer, trimmed + 1);
            return 1;
        }
        /* The schema's own message, which is the one the admin frontend will show for the same
         * field later. Written to stderr so a piped stdout stays clean. */
        (void)fprintf(stderr, "  %s\n", refusal);
    }
}

/** Adds one variable to what will be written. */
/*
 * Whether this secret comes from somewhere `setup` must not touch, saying so if it does.
 *
 * What this command does with an answer is why the question exists: it writes it into the
 * `.env`. For a secret that lives in the environment that is the whole point. For one systemd
 * keeps on a tmpfs, or one in a file with permissions of its own, it is wrong twice over --
 * the prompt has no value to offer, so an operator is asked for something already configured,
 * and the empty line that results becomes the password on the day the credential is taken
 * away. See contracts/secrets.json.
 */
static int keeps_its_own_secret(const char *name)
{
    const sc_secret_source source = sc_secret_source_of(name);

    if (source != SC_SECRET_CREDENTIAL && source != SC_SECRET_FILE)
        return 0;
    (void)fprintf(stdout, "  %s comes from %s -- leaving it alone\n", name,
                  source == SC_SECRET_CREDENTIAL ? "a systemd credential"
                                                 : "the file its _FILE variable names");
    return 1;
}

static void add(backend_setup_answers *setup, const char *name, const char *value)
{
    if (setup->entry_count >= BACKEND_SETUP_ENTRY_MAX)
        return;
    setup->entries[setup->entry_count].name = name;
    setup->entries[setup->entry_count].value = value;
    ++setup->entry_count;
}

/** Copies @p value into @p dst, which is always large enough for what this file puts there. */
static void set(char *dst, size_t dst_size, const char *value)
{
    size_t length = strlen(value);

    if (length + 1 > dst_size)
        length = dst_size - 1;
    memcpy(dst, value, length);
    dst[length] = '\0';
}

/**
 * Opens a session to the relay the answers name and says whether it answered.
 *
 * The same probe the backend runs at every start, run once here while the person who typed the
 * address is still standing at the terminal -- a wrong port found now is a correction, found at
 * the next start it is a search. @p maildev adds the one sentence that is only ever true of a
 * development setup: the container is part of this repository and starting it is one command.
 */
static void report_relay(const backend_setup_answers *setup, int maildev)
{
    sc_mail_env env;
    sc_mail_relay relay;
    sc_mail_session *session;
    char error[SC_MAIL_ERROR_MAX];
    sc_status status;

    if (strcmp(setup->email, "true") != 0)
        return;

    /* Built here rather than read from the environment: the answers have not been written
     * anywhere yet, and this is the moment they are worth checking. */
    memset(&env, 0, sizeof(env));
    env.enabled = 1;
    set(env.host, sizeof(env.host), setup->email_host);
    env.port = (uint16_t)strtoul(setup->email_port, NULL, 10);
    env.tls = SC_MAIL_TLS_NONE;
    if (strcmp(setup->email_tls, "starttls") == 0)
        env.tls = SC_MAIL_TLS_STARTTLS;
    else if (strcmp(setup->email_tls, "require") == 0)
        env.tls = SC_MAIL_TLS_REQUIRE;
    else if (strcmp(setup->email_tls, "implicit") == 0)
        env.tls = SC_MAIL_TLS_IMPLICIT;
    set(env.user, sizeof(env.user), setup->email_user);
    set(env.pass, sizeof(env.pass), setup->email_pass);
    set(env.sender, sizeof(env.sender), setup->email_sender);
    (void)snprintf(env.url, sizeof(env.url), "%s://%s:%s",
                   env.tls == SC_MAIL_TLS_IMPLICIT ? "smtps" : "smtp", env.host, setup->email_port);
    sc_mail_env_relay(&env, &relay);

    bk_say("\nAsking %s:%s whether it takes mail \xe2\x80\xa6", env.host, setup->email_port);
    (void)sc_mail_global_init();
    session = sc_mail_session_open();
    if (session == NULL) {
        bk_say("  it could not be asked: no session to open");
        return;
    }
    status = sc_mail_session_probe(session, &relay, error, sizeof(error));
    sc_mail_session_close(session);

    if (status == SC_OK) {
        bk_say("  it does.");
        if (maildev)
            bk_say("  What it receives is readable at http://localhost:%s.", MAILDEV_WEB_PORT);
        return;
    }
    bk_say("  it did not answer: %s", error);
    if (maildev) {
        bk_say("  That is the MailDev container of this repository, and it is not running.");
        bk_say("  Start it with: docker compose up -d maildev");
        bk_say("  The setup can be finished either way \xe2\x80\x94 nothing here needs it.");
    }
}

/** The value of @p name, or @p fallback when it is unset or empty. What a rerun of setup
 *  offers in the parentheses after a label. */
static const char *current(const char *name, const char *fallback)
{
    const char *value = getenv(name);

    return value != NULL && value[0] != '\0' ? value : fallback;
}

/** Whether @p name is among the variables to write already. */
static int decided(const backend_setup_answers *setup, const char *name)
{
    size_t i;

    for (i = 0; i != setup->entry_count; ++i) {
        if (strcmp(setup->entries[i].name, name) == 0)
            return 1;
    }
    return 0;
}

/**
 * Whether the environment names a database already -- out of `.env`, where setup wrote it the
 * last time, or out of whatever started the process.
 *
 * Any variable that says *which* database counts. The password and the pool size do not: on
 * their own they describe no database, only how to talk to one.
 */
static int is_database_configured(void)
{
    static const char *const kNames[] = {"DB_TYPE", "DB_FILE",     "DB_HOST",
                                         "DB_PORT", "DB_DATABASE", "DB_USER"};
    size_t i;

    for (i = 0; i != sizeof(kNames) / sizeof(kNames[0]); ++i) {
        if (current(kNames[i], NULL) != NULL)
            return 1;
    }
    return 0;
}

/**
 * The database @p setup names, on one line: what keeping it says, and what the development block
 * shows.
 *
 * The configured one while nothing was answered yet or when it was kept, the answered one
 * otherwise -- which is the same database backend_setup() goes on to open.
 */
static void describe_database(const backend_setup_answers *setup, char *out, size_t out_size)
{
    const int configured = setup->database_kept || setup->db_type[0] == '\0';
    const char *type = configured ? current("DB_TYPE", "sqlite") : setup->db_type;

    if (strcmp(type, "postgresql") != 0) {
        (void)snprintf(out, out_size, "sqlite in %s",
                       configured ? current("DB_FILE", DEFAULT_DB_FILE) : setup->db_file);
        return;
    }
    (void)snprintf(out, out_size, "postgresql, %s on %s:%s as %s",
                   configured ? current("DB_DATABASE", DEFAULT_DB_DATABASE) : setup->db_database,
                   configured ? current("DB_HOST", DEFAULT_DB_HOST) : setup->db_host,
                   configured ? current("DB_PORT", DEFAULT_DB_PORT) : setup->db_port,
                   configured ? current("DB_USER", DEFAULT_DB_USER) : setup->db_user);
}

/**
 * What a developer's machine is, without asking -- beyond the database, which was asked.
 *
 * `http://localhost` because that is what a checkout runs as, and the MailDev container because
 * it is the mail sink this repository ships: nothing is delivered, every mail is readable at
 * http://localhost:1081, and there are no credentials because the container is started without
 * any.
 */
static void development_setup(backend_setup_answers *setup)
{
    set(setup->community.name, sizeof(setup->community.name), DEVELOPMENT_COMMUNITY_NAME);
    setup->community.has_description = 0;
    set(setup->community.url, sizeof(setup->community.url), DEVELOPMENT_COMMUNITY_URL);

    set(setup->node_env, sizeof(setup->node_env), "development");
    set(setup->email, sizeof(setup->email), "true");
    set(setup->email_host, sizeof(setup->email_host), "localhost");
    set(setup->email_port, sizeof(setup->email_port), MAILDEV_SMTP_PORT);
    /* MailDev speaks no TLS and asks for no password. Anything else here would be a handshake
     * it answers with a refusal. */
    set(setup->email_tls, sizeof(setup->email_tls), "none");
    set(setup->email_user, sizeof(setup->email_user), "");
    set(setup->email_pass, sizeof(setup->email_pass), "");
    set(setup->email_sender, sizeof(setup->email_sender), "dev@gradido.localhost");
    set(setup->email_sender_name, sizeof(setup->email_sender_name), DEVELOPMENT_COMMUNITY_NAME);

    add(setup, "NODE_ENV", setup->node_env);
    add(setup, "EMAIL", setup->email);
    add(setup, "EMAIL_SMTP_HOST", setup->email_host);
    add(setup, "EMAIL_SMTP_PORT", setup->email_port);
    add(setup, "EMAIL_SMTP_TLS", setup->email_tls);
    add(setup, "EMAIL_USERNAME", setup->email_user);
    if (!keeps_its_own_secret("EMAIL_PASSWORD"))
        add(setup, "EMAIL_PASSWORD", setup->email_pass);
    add(setup, "EMAIL_SENDER", setup->email_sender);
    add(setup, "EMAIL_SENDER_NAME", setup->email_sender_name);
}

/**
 * Takes the development proposal back, so that asking field by field starts from nothing --
 * except the database, which was asked rather than proposed. Its variables are the first
 * @p decided_count entries, and so are all that stay.
 */
static void forget_proposal(backend_setup_answers *setup, size_t decided_count)
{
    setup->entry_count = decided_count;
    memset(&setup->community, 0, sizeof(setup->community));
    setup->node_env[0] = '\0';
    setup->email[0] = '\0';
    setup->email_host[0] = '\0';
    setup->email_port[0] = '\0';
    setup->email_tls[0] = '\0';
    setup->email_user[0] = '\0';
    setup->email_pass[0] = '\0';
    setup->email_sender[0] = '\0';
    setup->email_sender_name[0] = '\0';
}

static void describe(const backend_setup_answers *setup)
{
    char database[SC_DB_HOST_MAX + SC_DB_NAME_MAX + SC_DB_USER_MAX + 32];

    describe_database(setup, database, sizeof(database));
    bk_say("\nThese are the development settings:\n");
    bk_say("  community name  %s", setup->community.name);
    bk_say("  public URL      %s", setup->community.url);
    bk_say("  database        %s", database);
    bk_say("  mail relay      %s:%s, no TLS, no login", setup->email_host, setup->email_port);
    bk_say("  sender          %s <%s>", setup->email_sender_name, setup->email_sender);
}

/**
 * Says which of the two ports a PostgreSQL answers on, and answers how many do. @p container is
 * set when the one that does is the port docker-compose.yml publishes.
 *
 * Something that answers and is not PostgreSQL is said as well: it is the reason a server
 * pointed at that port would fail, and finding that out now is cheaper than at the first start.
 */
static int report_postgres(int *container)
{
    static const int kPorts[] = {BK_POSTGRES_DEFAULT_PORT, BK_POSTGRES_COMPOSE_PORT};
    int found = 0;
    size_t i;

    *container = 0;
    bk_say("\nLooking for PostgreSQL on this machine \xe2\x80\xa6");
    for (i = 0; i != sizeof(kPorts) / sizeof(kPorts[0]); ++i) {
        const bk_postgres_answer answer =
            bk_postgres_probe(BK_POSTGRES_LOOPBACK, kPorts[i], BK_POSTGRES_PROBE_TIMEOUT_MS);
        char where[32];

        (void)snprintf(where, sizeof(where), "localhost:%d", kPorts[i]);
        bk_say("  %-16s %s \xe2\x80\x94 %s", where,
               answer == BK_POSTGRES_FOUND   ? "PostgreSQL answers"
               : answer == BK_POSTGRES_OTHER ? "something answers, and it is not PostgreSQL"
                                             : "nothing answers",
               kPorts[i] == BK_POSTGRES_DEFAULT_PORT
                   ? "the port PostgreSQL listens on unless told otherwise"
                   : "the port docker-compose.yml publishes it on");
        if (answer == BK_POSTGRES_FOUND) {
            ++found;
            if (kPorts[i] == BK_POSTGRES_COMPOSE_PORT)
                *container = 1;
        }
    }
    return found;
}

/**
 * The questions for PostgreSQL, with what they propose depending on what was found.
 *
 * What is configured, when it is PostgreSQL already -- somebody who chose it over keeping it is
 * changing one value. Otherwise, when the container of docker-compose.yml answers, what that
 * container was started with: its port, and the user, password and database it reads from the
 * same variables -- or their defaults. A server on 5432 changes nothing about the proposal: the
 * default is already the socket directory of a server on this machine, which is where that one
 * is fastest, see contracts/database-config.json, rules.connection.
 */
static int ask_for_postgres(backend_setup_answers *setup, int container_found)
{
    const int container =
        strcmp(current("DB_TYPE", "sqlite"), "postgresql") != 0 && container_found;
    const char *configured_password = current("DB_PASSWORD", "");
    const char *proposed_password = container && configured_password[0] == '\0'
                                        ? DOCKER_COMPOSE_POSTGRES_PASSWORD
                                        : configured_password;
    char compose_port[8];
    char shown[64];

    (void)snprintf(compose_port, sizeof(compose_port), "%d", BK_POSTGRES_COMPOSE_PORT);
    (void)snprintf(shown, sizeof(shown), "%s, what docker-compose.yml sets", proposed_password);

    if (!ask("Database host", container ? "localhost" : current("DB_HOST", DEFAULT_DB_HOST),
             ANSWER_REQUIRED, setup->db_host, sizeof(setup->db_host)))
        return 0;
    add(setup, "DB_HOST", setup->db_host);
    if (!ask("Database port", container ? compose_port : current("DB_PORT", DEFAULT_DB_PORT),
             ANSWER_PORT, setup->db_port, sizeof(setup->db_port)))
        return 0;
    add(setup, "DB_PORT", setup->db_port);
    if (!ask("Database name", current("DB_DATABASE", DEFAULT_DB_DATABASE), ANSWER_REQUIRED,
             setup->db_database, sizeof(setup->db_database)))
        return 0;
    add(setup, "DB_DATABASE", setup->db_database);
    if (!ask("Database user", current("DB_USER", DEFAULT_DB_USER), ANSWER_REQUIRED, setup->db_user,
             sizeof(setup->db_user)))
        return 0;
    add(setup, "DB_USER", setup->db_user);
    /* Only where the environment is the source. Writing an empty line for a secret that comes
     * from elsewhere would put a password nobody chose into the file. */
    if (keeps_its_own_secret("DB_PASSWORD"))
        return 1;
    if (!bk_prompt_secret("Database password", proposed_password,
                          proposed_password == configured_password ? NULL : shown,
                          setup->db_password, sizeof(setup->db_password)))
        return 0;
    add(setup, "DB_PASSWORD", setup->db_password);
    return 1;
}

/**
 * Which database, and where -- its variables among the entries, or none at all when what is
 * configured already is kept.
 *
 * Kept means not written: the lines that configure it stay exactly as they are, wherever they
 * came from, and backend_setup() reads them back out of the environment.
 */
static int ask_for_database(backend_setup_answers *setup)
{
    static const char *const kLabels[] = {"as configured", "sqlite", "postgresql"};
    static const char *const kHints[] = {"the database above", "one file, nothing to install",
                                         "a server that has to be installed and running"};
    enum { KEEP, SQLITE, POSTGRESQL };
    const int configured = is_database_configured();
    /* The list starts at "as configured" only when there is something to keep. */
    const int first = configured ? KEEP : SQLITE;
    int container = 0;
    const int found = report_postgres(&container);
    int proposed;
    int chosen;

    if (configured) {
        char database[SC_DB_HOST_MAX + SC_DB_NAME_MAX + SC_DB_USER_MAX + 32];

        describe_database(setup, database, sizeof(database));
        bk_say("\nThe database is configured already:");
        bk_say("  %s", database);
    }
    bk_say("\nSQLite keeps the whole database in one file beside the server and needs nothing");
    bk_say("else. PostgreSQL is the reference, for a community with an administrator; it is a");
    bk_say("server of its own, and it has to be installed and running before this one starts.");

    /* What is configured before what is running: a rerun is somebody changing one thing, and a
     * server that happens to be up is not a reason to move their data somewhere else. */
    proposed = configured ? KEEP : found != 0 ? POSTGRESQL : SQLITE;
    chosen = bk_prompt_choose("Which database?", kLabels + first, kHints + first, 3 - first,
                              proposed - first);
    if (chosen < 0)
        return 0;
    chosen += first;

    if (chosen == KEEP) {
        setup->database_kept = 1;
        return 1;
    }
    set(setup->db_type, sizeof(setup->db_type), kLabels[chosen]);
    add(setup, "DB_TYPE", setup->db_type);
    if (chosen == POSTGRESQL)
        return ask_for_postgres(setup, container);

    if (!ask("Database file", current("DB_FILE", DEFAULT_DB_FILE), ANSWER_REQUIRED, setup->db_file,
             sizeof(setup->db_file)))
        return 0;
    add(setup, "DB_FILE", setup->db_file);
    return 1;
}

/**
 * The rule sc_db_config_load applies at every start, applied here instead: a password refused now
 * costs one more question, refused at the next start it costs a server that will not come up.
 * Asked of the database as it will be -- answered or kept -- because a kept one is held to the
 * same rule, and only a production installation is asked it at all.
 */
static int insist_on_production_password(backend_setup_answers *setup)
{
    for (;;) {
        const int kept = setup->database_kept;
        const char *type = kept ? current("DB_TYPE", "sqlite") : setup->db_type;
        const char *host = kept ? current("DB_HOST", DEFAULT_DB_HOST) : setup->db_host;
        const char *password =
            decided(setup, "DB_PASSWORD") ? setup->db_password : current("DB_PASSWORD", "");

        if (strcmp(type, "postgresql") != 0 || sc_db_host_is_unix_socket(host) ||
            password[0] != '\0' || keeps_its_own_secret("DB_PASSWORD"))
            return 1;
        (void)fprintf(stderr, "  %s\n", DATABASE_PASSWORD_MESSAGE);
        if (!bk_prompt_secret("Database password", "", NULL, setup->db_password,
                              sizeof(setup->db_password)))
            return 0;
        if (!decided(setup, "DB_PASSWORD"))
            add(setup, "DB_PASSWORD", setup->db_password);
    }
}

static int ask_for_email(backend_setup_answers *setup)
{
    static const char *const kLabels[] = {"require", "starttls", "implicit", "none"};
    static const char *const kHints[] = {
        "STARTTLS, and refuse the relay without it", "STARTTLS where offered, plain where not",
        "TLS from the first byte, which is port 465", "plain, for a relay on this machine"};
    const char *configured = current("EMAIL_SMTP_TLS", "starttls");
    int sends = bk_prompt_yes_no("Does this instance send mail?",
                                 strcmp(current("EMAIL", "false"), "true") == 0);
    int chosen;
    int i;

    if (sends < 0)
        return 0;
    set(setup->email, sizeof(setup->email), sends ? "true" : "false");
    add(setup, "EMAIL", setup->email);
    if (!sends)
        return 1;

    if (!ask("SMTP host", current("EMAIL_SMTP_HOST", "localhost"), ANSWER_REQUIRED,
             setup->email_host, sizeof(setup->email_host)))
        return 0;
    if (!ask("SMTP port", current("EMAIL_SMTP_PORT", "587"), ANSWER_PORT, setup->email_port,
             sizeof(setup->email_port)))
        return 0;

    chosen = 1;
    for (i = 0; i != 4; ++i) {
        if (strcmp(configured, kLabels[i]) == 0)
            chosen = i;
    }
    chosen =
        bk_prompt_choose("How is the session to the relay encrypted?", kLabels, kHints, 4, chosen);
    if (chosen < 0)
        return 0;
    set(setup->email_tls, sizeof(setup->email_tls), kLabels[chosen]);

    if (!ask("SMTP user, empty for a relay that wants none", current("EMAIL_USERNAME", ""),
             ANSWER_OPTIONAL, setup->email_user, sizeof(setup->email_user)))
        return 0;
    /* Not asked when there is no user to go with it: SMTP AUTH is a pair, and a password on its
     * own authenticates as nobody. */
    if (setup->email_user[0] == '\0')
        setup->email_pass[0] = '\0';
    else if (!keeps_its_own_secret("EMAIL_PASSWORD") &&
             !bk_prompt_secret("SMTP password", current("EMAIL_PASSWORD", ""), NULL,
                               setup->email_pass, sizeof(setup->email_pass)))
        return 0;
    if (!ask("Sender address", current("EMAIL_SENDER", ""), ANSWER_EMAIL, setup->email_sender,
             sizeof(setup->email_sender)))
        return 0;
    if (!ask("Sender name", current("EMAIL_SENDER_NAME", setup->community.name), ANSWER_OPTIONAL,
             setup->email_sender_name, sizeof(setup->email_sender_name)))
        return 0;

    add(setup, "EMAIL_SMTP_HOST", setup->email_host);
    add(setup, "EMAIL_SMTP_PORT", setup->email_port);
    add(setup, "EMAIL_SMTP_TLS", setup->email_tls);
    add(setup, "EMAIL_USERNAME", setup->email_user);
    if (!keeps_its_own_secret("EMAIL_PASSWORD"))
        add(setup, "EMAIL_PASSWORD", setup->email_pass);
    add(setup, "EMAIL_SENDER", setup->email_sender);
    add(setup, "EMAIL_SENDER_NAME", setup->email_sender_name);
    return 1;
}

static int ask_every_field(backend_setup_answers *setup, int production)
{
    size_t description_length;

    bk_say("\nEvery question shows what it would take in parentheses; Enter takes it,");
    bk_say("anything else replaces it.\n");

    if (!ask("Community name", DEVELOPMENT_COMMUNITY_NAME, ANSWER_NAME, setup->community.name,
             sizeof(setup->community.name)))
        return 0;
    if (!ask("Description (optional)", "", ANSWER_DESCRIPTION, setup->community.description,
             sizeof(setup->community.description)))
        return 0;
    /* Empty means absent rather than an empty string: the column is nullable and "" in it would
     * be a third state that every reader has to remember to handle. */
    description_length = strlen(setup->community.description);
    setup->community.has_description = description_length != 0;
    if (!ask("Public URL, e.g. https://gdd.example.org", "", ANSWER_URL, setup->community.url,
             sizeof(setup->community.url)))
        return 0;

    set(setup->node_env, sizeof(setup->node_env), production ? "production" : "development");
    add(setup, "NODE_ENV", setup->node_env);
    if (!ask_for_email(setup))
        return 0;

    report_relay(setup, 0);
    return 1;
}

static int hold_conversation(backend_setup_answers *setup)
{
    static const char *const kLabels[] = {"development", "production"};
    static const char *const kHints[] = {"localhost, mail into the MailDev container",
                                         "every value is asked for"};
    const char *node_env = getenv("NODE_ENV");
    size_t database_entries;
    int production;

    bk_say("\nThis database has no community yet.\n");
    bk_say("What follows is written once and becomes this instance's identity: other");
    bk_say("communities will know it by these answers and by a key pair generated here.");
    bk_say("The database and the mail relay are written to .env beside it.");

    if (!ask_for_database(setup))
        return 0;

    production = bk_prompt_choose("What kind of installation is this?", kLabels, kHints, 2,
                                  node_env != NULL && strcmp(node_env, "production") == 0 ? 1 : 0);
    if (production < 0)
        return 0;
    if (production && !insist_on_production_password(setup))
        return 0;
    database_entries = setup->entry_count;

    if (!production) {
        int take;

        development_setup(setup);
        describe(setup);
        report_relay(setup, 1);
        take = bk_prompt_yes_no("Take them?", 1);
        if (take < 0)
            return 0;
        if (take)
            return 1;
        forget_proposal(setup, database_entries);
    }

    return ask_every_field(setup, production);
}

int backend_ask_for_setup(backend_setup_answers *setup)
{
    int answered;

    if (setup == NULL)
        return 0;
    memset(setup, 0, sizeof(*setup));

    /* Without a terminal there is nobody to answer, and a command that blocked on a prompt
     * nobody can see would look like a hang rather than an unfinished setup. The caller turns
     * this into a line that says what to do instead. */
    if (!bk_prompt_is_terminal())
        return 0;

    bk_prompt_begin();
    answered = hold_conversation(setup);
    bk_prompt_end();
    return answered;
}

sc_status backend_ask_for_master_seed(backend_setup_answers *setup,
                                      uint8_t seed[SC_MASTER_SEED_BYTES])
{
    /* Longer than a seed, so that a value that is too long is reported as not being one. */
    char current[2 * SC_MASTER_SEED_HEX_SIZE];
    char typed[256];
    sc_status status;

    if (setup == NULL || seed == NULL)
        return SC_ERR_INVALID_ARGUMENT;

    status = sc_secret_read("MASTER_SEED", current, sizeof(current));
    if (status == SC_ERR_UNAVAILABLE)
        return status;
    if (status != SC_OK || sc_secret_source_of("MASTER_SEED") != SC_SECRET_NOWHERE) {
        const int parsed = status == SC_OK && sc_master_seed_parse(current, seed);
        sodium_memzero(current, sizeof(current));
        return parsed ? SC_OK : SC_ERR_MALFORMED;
    }

    bk_say("\nThis instance needs a master seed: the root of the keys it derives, its peer");
    bk_say("network identity first. The system's randomness makes it; whatever you type");
    bk_say("now is mixed in as well.\n");
    typed[0] = '\0';
    bk_prompt_begin();
    (void)bk_prompt_secret("Type some random keys", "", "optional", typed, sizeof(typed));
    bk_prompt_end();

    status = sc_master_seed_new(typed, seed);
    sodium_memzero(typed, sizeof(typed));
    if (status != SC_OK)
        return status;
    sc_master_seed_to_hex(seed, setup->master_seed);
    add(setup, "MASTER_SEED", setup->master_seed);
    return SC_OK;
}
