/*
 * The first start against an empty database: ask the admin who this community is.
 *
 * Legacy reads COMMUNITY_NAME and COMMUNITY_DESCRIPTION out of the environment at every start.
 * gradido2 asks once and writes a row, because these are not settings -- they are the identity of
 * a community, written once and then referred to. An environment variable that has silently
 * drifted from the row it created is a confusion that does not need to exist, and the key pair
 * that goes with the row could never have come from an env file anyway.
 *
 * **Only what a person knows is asked.** The uuid, the ed25519 key pair and the timestamps are
 * generated by the interaction; a prompt for any of them would be a way to get them wrong.
 *
 * Each answer is checked against the same rules an admin route will later check a rename
 * against, and a rejected answer is asked again rather than ending the setup -- somebody is
 * standing at the terminal, and losing two correct answers because the third had a typo would be
 * gratuitous.
 */
#include "setup.h"

#include <stdio.h>
#include <string.h>

#if defined(_WIN32)
#include <io.h>
#define bk_isatty(stream) _isatty(_fileno(stream))
#else
#include <unistd.h>
#define bk_isatty(stream) isatty(fileno(stream))
#endif

#include "field_rules.h"

/** One line of an answer. Longer than any column here, so that a value that is too long is
 *  refused by the rule that says so rather than by the buffer. */
#define ANSWER_MAX 2048

/** The rules of packages/shared/src/schemas/community.ts, in the order those pipes apply them. */
typedef enum answer_kind { ANSWER_NAME, ANSWER_DESCRIPTION, ANSWER_URL } answer_kind;

/**
 * Whether @p text is a URL by the rule `v.url()` applies, which is whether `new URL(text)`
 * parses.
 *
 * Approximated rather than reproduced: the WHATWG parser is a specification, not a predicate, and
 * carrying it here to accept `mailto:x` -- which that rule does accept -- would buy nothing this
 * prompt wants. What is checked is a scheme, a colon, and, for the schemes that must have one, a
 * host. The difference is a value the reference path would take and this one asks again about,
 * on an interactive prompt, and it is written down here rather than left to be discovered.
 */
static int is_url(const char *text, size_t length)
{
    static const char *const kSpecial[] = {"http", "https", "ws", "wss", "ftp"};
    size_t scheme = 0;
    size_t host = 0;
    size_t i;

    if (length == 0)
        return 0;
    if (!((text[0] >= 'A' && text[0] <= 'Z') || (text[0] >= 'a' && text[0] <= 'z')))
        return 0;
    while (scheme < length && text[scheme] != ':') {
        char c = text[scheme];
        if (!((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') ||
              c == '+' || c == '-' || c == '.'))
            return 0;
        ++scheme;
    }
    if (scheme == length || scheme == 0)
        return 0;
    /* Something has to follow the colon; `http:` on its own is not a URL to anybody. */
    if (scheme + 1 == length)
        return 0;

    for (i = 0; i != sizeof(kSpecial) / sizeof(kSpecial[0]); ++i) {
        size_t len = strlen(kSpecial[i]);
        size_t start;

        if (len != scheme)
            continue;
        {
            size_t c;
            for (c = 0; c != len; ++c) {
                char left = text[c];
                if (left >= 'A' && left <= 'Z')
                    left = (char)(left - 'A' + 'a');
                if (left != kSpecial[i][c])
                    break;
            }
            if (c != len)
                continue;
        }
        /* A special scheme needs a host, and the "//" before it is optional only in the sense
         * that the parser inserts it -- either way there has to be something to connect to. */
        start = scheme + 1;
        while (start < length && text[start] == '/')
            ++start;
        while (start + host < length && text[start + host] != '/' && text[start + host] != '?' &&
               text[start + host] != '#')
            ++host;
        return host != 0;
    }
    return 1;
}

/**
 * Reads one answer and checks it. Returns 1 when @p out holds an acceptable value, and 0 at the
 * end of input -- which is a terminal that went away mid-setup, not an answer.
 */
static int ask(const char *label, answer_kind kind, char *out, size_t out_size, int *has_value)
{
    char line[ANSWER_MAX];

    for (;;) {
        const char *refusal = NULL;
        size_t begin = 0;
        size_t trimmed = 0;
        size_t units;
        size_t length;

        (void)fprintf(stdout, "%s: ", label);
        (void)fflush(stdout);
        if (fgets(line, sizeof(line), stdin) == NULL)
            return 0;
        length = strlen(line);
        while (length != 0 && (line[length - 1] == '\n' || line[length - 1] == '\r'))
            line[--length] = '\0';

        bk_trim(line, length, &begin, &trimmed);
        units = bk_utf16_length(line + begin, trimmed);

        switch (kind) {
        case ANSWER_NAME:
            /* nonEmpty before maxLength, which is the order communityNameSchema pipes them. */
            if (trimmed == 0)
                refusal = "This field is required";
            else if (units > 40)
                refusal = "This name is too long";
            break;
        case ANSWER_DESCRIPTION:
            if (units > 255)
                refusal = "This description is too long";
            break;
        case ANSWER_URL:
        default:
            if (trimmed == 0)
                refusal = "This field is required";
            else if (units > 255)
                refusal = "This URL is too long";
            else if (!is_url(line + begin, trimmed))
                refusal = "Please enter a valid URL, including https://";
            break;
        }
        if (refusal == NULL && trimmed + 1 > out_size)
            refusal = "This value is too long";
        if (refusal != NULL) {
            /* The schema's own message, which is the one the admin frontend will show for the
             * same field later. Written to stderr so a piped stdout stays clean. */
            (void)fprintf(stderr, "  %s\n", refusal);
            continue;
        }
        memcpy(out, line + begin, trimmed);
        out[trimmed] = '\0';
        /* Empty means absent rather than an empty string: the column is nullable and "" in it
         * would be a third state that every reader has to remember to handle. */
        if (has_value != NULL)
            *has_value = trimmed != 0;
        return 1;
    }
}

int backend_ask_for_home_community(bc_home_community_setup *setup)
{
    /* Without a terminal there is nobody to answer, and a process that blocked on a prompt
     * nobody can see would look like a hung start rather than an unfinished setup. The caller
     * turns this into a line that says what to do instead. */
    if (!bk_isatty(stdin) || !bk_isatty(stdout))
        return 0;

    (void)fprintf(
        stdout, "\nThis database has no community yet.\n\n"
                "What follows is written once and becomes this instance's identity: other\n"
                "communities will know it by these answers and by a key pair generated here.\n\n");

    if (!ask("Community name", ANSWER_NAME, setup->name, sizeof(setup->name), NULL))
        return 0;
    if (!ask("Description (optional)", ANSWER_DESCRIPTION, setup->description,
             sizeof(setup->description), &setup->has_description))
        return 0;
    if (!ask("Public URL, e.g. https://gdd.example.org", ANSWER_URL, setup->url, sizeof(setup->url),
             NULL))
        return 0;
    return 1;
}
