/*
 * The frontends, in the binary.
 *
 * A Gradido server hands out the pages it serves: `Architecture.md` has a deployment as one
 * binary next to a database, so there is no nginx in front of it and no second process that
 * only serves files. Both implementations therefore carry the same static web server, and both
 * carry the same files -- `publish/`, which `bun run publish` assembles out of `packages/`.
 * Neither implementation can build a page: a page is vite's output, and this path has no
 * JavaScript in it at all.
 *
 * `static_sites_data.gen.c` is generated by build.zig (and by CMakeLists.txt for the MSVC
 * build) out of `publish/sites.json` at configure time, and is never checked in. **The
 * manifest is where the content type and the ETag come from**, not this code: two static
 * servers that inferred a type from an extension separately would disagree about one of them
 * eventually, and two that hashed the bytes separately would disagree about all of them. What
 * a client gets must not depend on which implementation is deployed. It also means nothing
 * here computes anything per request -- the bytes were fixed when the build ran.
 *
 * A build without pages -- `zig build -Dpages=false`, and every build on a machine with no bun
 * -- gets the same table with no sites in it. The server then answers every path the way it
 * did before there were any: ROUTE_NOT_IMPLEMENTED, out of the default route.
 *
 * `packages/backend/src/server/staticRoutes.ts` is the same rules in TypeScript, against the
 * same manifest.
 */
#ifndef BACKEND_STATIC_SITES_H
#define BACKEND_STATIC_SITES_H

#include <stddef.h>

#include "service_core/http.h"

/** One file of one site. @ref bytes outlives the process -- it is in the executable. */
typedef struct backend_static_file {
    /** Path below the site's own root, '/' separated: "assets/index-Ca4jjj45.js". */
    const char *path;
    size_t path_length;
    const char *bytes;
    size_t length;
    /** The Content-Type header, charset included, as `publish/sites.json` gave it. */
    const char *content_type;
    /** The ETag *with* its quotes, so that serving it is a copy and comparing it is a memcmp. */
    const char *etag;
    /** Whether the name carries a content hash and the file may be cached for a year. */
    int immutable;
} backend_static_file;

/** One built frontend: the user app at the root, the admin app under a sub-path. */
typedef struct backend_static_site {
    const char *name;
    /** Where the site is mounted: "" for the domain root, "/admin" for a sub-path. */
    const char *base_path;
    size_t base_path_length;
    /** Sorted by path, which is what lets the lookup below be a binary search. */
    const backend_static_file *files;
    size_t file_count;
    /** The app's entry document, served for every path the site has no file for. */
    const backend_static_file *index;
} backend_static_site;

/** What this build was given. Empty when it was built without pages. */
extern const backend_static_site backend_static_sites[];
extern const size_t backend_static_site_count;

/**
 * The site @p path belongs to: the longest @ref base_path it starts with, so "/admin/x" goes
 * to the admin app and everything else to the one mounted at the root. NULL when no site
 * claims it, which with no sites at all is every path.
 */
const backend_static_site *backend_static_site_for(const backend_static_site *sites, size_t count,
                                                   const char *path, size_t path_length);

/**
 * The file at @p path below @p site, or NULL. @p path is relative to the site's root and is not
 * NUL terminated.
 *
 * Nothing here defends against "../../etc/passwd" because there is nothing to defend: the table
 * holds the files the build put in it, and a path that is not one of them is not found. Binary
 * search, because a site is a few dozen entries and every page load asks several times.
 */
const backend_static_file *backend_static_file_find(const backend_static_site *site,
                                                    const char *path, size_t path_length);

/**
 * Serves @p req out of the sites this binary carries.
 *
 * @return 0 when it answered, -1 when this is not a request for a page -- which the caller
 *         turns into the contracted ROUTE_NOT_IMPLEMENTED. @p user_data is ignored.
 *
 * Registered as part of the default route rather than as a route of its own: a static server
 * that answered before the routes would shadow them, and one that answered a 404 itself would
 * take ROUTE_NOT_IMPLEMENTED away from the 139 contracted paths that are still unwritten.
 * `backend/src/backend.c` is where the order is decided.
 */
int backend_static_serve(sc_http_req *req, void *user_data);

#endif /* BACKEND_STATIC_SITES_H */
