/*
 * contracts/migrations/, in the binary.
 *
 * The migrations are a contract and not this implementation's property: the TypeScript path
 * opens the same database and builds the same schema, so the SQL is a plain `.sql` file either
 * language reads and the order is a JSON file either language parses. What differs is only how
 * the files get into a process, and both paths answer that the same way -- they are embedded,
 * not read from disk. `Architecture.md` requires each implementation to stay shippable as a
 * single binary, and a file read at runtime is not in one; the TypeScript path uses a text
 * import, this one has its build write them out as C.
 *
 * `migrations_data.gen.c` is generated by build.zig (and by CMakeLists.txt for the MSVC build)
 * out of `../contracts/migrations`, at configure time, and is never checked in. It carries every
 * file under that directory, `index.json` included -- deliberately more than the contract names,
 * because *which* migrations exist is decided by index.json at runtime and not by what the build
 * happened to find. A file the contract names and the table does not carry is an error naming
 * it; a file the table carries and the contract does not name is never looked at.
 */
#ifndef BACKEND_CORE_CONTRACT_FILES_H
#define BACKEND_CORE_CONTRACT_FILES_H

#include <stddef.h>

/** One embedded file. @ref bytes is NUL terminated beyond @ref length, so a parser that wants
 *  a C string and one that wants a length are both served without a copy. */
typedef struct bc_contract_file {
    /** Path below contracts/migrations, '/' separated on every host. */
    const char *path;
    const char *bytes;
    size_t length;
} bc_contract_file;

extern const bc_contract_file bc_migration_files[];
extern const size_t bc_migration_file_count;

/** The file at @p path, or NULL. Linear: there are eight of them and the lookup happens once,
 *  at startup, per migration. */
const bc_contract_file *bc_contract_file_find(const char *path);

#endif /* BACKEND_CORE_CONTRACT_FILES_H */
