/* GENERATED by packages/email-native/tools/gen_c.mjs -- do not edit.
 * Source: the pug templates in packages/email-native/templates.
 * Regenerate with `turbo @gradido/email-native#build`.
 */
#ifndef SERVICE_CORE_EMAIL_GEN_H
#define SERVICE_CORE_EMAIL_GEN_H

#include "service_core/email.h"

typedef enum {
    GE_LOCALE_EN = 0,
    GE_LOCALE_DE = 1,
    GE_LOCALE_ES = 2,
    GE_LOCALE_FR = 3,
    GE_LOCALE_NL = 4,
    GE_LOCALE_IT = 5,
    GE_LOCALE_TR = 6,
    GE_LOCALE_RU = 7,
    GE_LOCALE_PT = 8,
    GE_LOCALE_EL = 9,
    GE_LOCALE_COUNT = 10
} ge_locale_t;

typedef enum {
    GE_TPL_ACCOUNT_ACTIVATION = 0,
    GE_TPL_ACCOUNT_MULTI_REGISTRATION = 1,
    GE_TPL_ADDED_CONTRIBUTION_MESSAGE = 2,
    GE_TPL_ASSISTED_REGISTRATION_CONFIRM = 3,
    GE_TPL_CONTRIBUTION_CHANGED_BY_MODERATOR = 4,
    GE_TPL_CONTRIBUTION_CONFIRMED = 5,
    GE_TPL_CONTRIBUTION_DELETED = 6,
    GE_TPL_CONTRIBUTION_DENIED = 7,
    GE_TPL_CUSTOM_EMAIL = 8,
    GE_TPL_EMAIL_CHANGE_CONFIRM = 9,
    GE_TPL_EMAIL_CHANGE_DONE = 10,
    GE_TPL_EMAIL_CHANGE_NOTICE = 11,
    GE_TPL_EMAIL_CHANGE_SUPPORT = 12,
    GE_TPL_RESET_PASSWORD = 13,
    GE_TPL_THANK_YOU_CARD_PAID = 14,
    GE_TPL_TRANSACTION_LINK_REDEEMED = 15,
    GE_TPL_TRANSACTION_RECEIVED = 16,
    GE_TPL_COUNT = 17
} ge_template_t;

/* accountActivation */
typedef struct {
    const char *activation_link;
    const char *first_name;
    const char *hours;
    const char *last_name;
    const char *logo_url;
    const char *minutes;
    const char *resend_link;
} ge_account_activation_t;

int ge_render_account_activation(ge_locale_t locale, const ge_account_activation_t *v, ge_mail_t *out);
int ge_render_account_activation_into(ge_locale_t locale, const ge_account_activation_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_account_activation_into_fast(ge_locale_t locale, const ge_account_activation_t *v, ge_arena_t *a, ge_mail_t *out);

/* accountMultiRegistration */
typedef struct {
    const char *first_name;
    const char *helper_link;
    const char *last_name;
    const char *resend_link;
    const char *support_email;
} ge_account_multi_registration_t;

int ge_render_account_multi_registration(ge_locale_t locale, const ge_account_multi_registration_t *v, ge_mail_t *out);
int ge_render_account_multi_registration_into(ge_locale_t locale, const ge_account_multi_registration_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_account_multi_registration_into_fast(ge_locale_t locale, const ge_account_multi_registration_t *v, ge_arena_t *a, ge_mail_t *out);

/* addedContributionMessage */
typedef struct {
    const char *community_url;
    const char *contribution_frontend_link;
    const char *contribution_memo;
    const char *first_name;
    const char *last_name;
    const char *message;
    const char *sender_alias;
} ge_added_contribution_message_t;

int ge_render_added_contribution_message(ge_locale_t locale, const ge_added_contribution_message_t *v, ge_mail_t *out);
int ge_render_added_contribution_message_into(ge_locale_t locale, const ge_added_contribution_message_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_added_contribution_message_into_fast(ge_locale_t locale, const ge_added_contribution_message_t *v, ge_arena_t *a, ge_mail_t *out);

/* assistedRegistrationConfirm */
typedef struct {
    const char *confirm_link;
    const char *first_name;
    const char *hours;
    const char *last_name;
    const char *minutes;
} ge_assisted_registration_confirm_t;

int ge_render_assisted_registration_confirm(ge_locale_t locale, const ge_assisted_registration_confirm_t *v, ge_mail_t *out);
int ge_render_assisted_registration_confirm_into(ge_locale_t locale, const ge_assisted_registration_confirm_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_assisted_registration_confirm_into_fast(ge_locale_t locale, const ge_assisted_registration_confirm_t *v, ge_arena_t *a, ge_mail_t *out);

/* contributionChangedByModerator */
typedef struct {
    const char *contribution_frontend_link;
    const char *contribution_memo;
    const char *contribution_memo_updated;
    const char *first_name;
    const char *last_name;
    const char *sender_alias;
} ge_contribution_changed_by_moderator_t;

int ge_render_contribution_changed_by_moderator(ge_locale_t locale, const ge_contribution_changed_by_moderator_t *v, ge_mail_t *out);
int ge_render_contribution_changed_by_moderator_into(ge_locale_t locale, const ge_contribution_changed_by_moderator_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_contribution_changed_by_moderator_into_fast(ge_locale_t locale, const ge_contribution_changed_by_moderator_t *v, ge_arena_t *a, ge_mail_t *out);

/* contributionConfirmed */
typedef struct {
    const char *contribution_amount;
    const char *contribution_frontend_link;
    const char *contribution_memo;
    const char *first_name;
    const char *last_name;
    const char *sender_alias;
} ge_contribution_confirmed_t;

int ge_render_contribution_confirmed(ge_locale_t locale, const ge_contribution_confirmed_t *v, ge_mail_t *out);
int ge_render_contribution_confirmed_into(ge_locale_t locale, const ge_contribution_confirmed_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_contribution_confirmed_into_fast(ge_locale_t locale, const ge_contribution_confirmed_t *v, ge_arena_t *a, ge_mail_t *out);

/* contributionDeleted */
typedef struct {
    const char *contribution_frontend_link;
    const char *contribution_memo;
    const char *first_name;
    const char *last_name;
    const char *sender_alias;
} ge_contribution_deleted_t;

int ge_render_contribution_deleted(ge_locale_t locale, const ge_contribution_deleted_t *v, ge_mail_t *out);
int ge_render_contribution_deleted_into(ge_locale_t locale, const ge_contribution_deleted_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_contribution_deleted_into_fast(ge_locale_t locale, const ge_contribution_deleted_t *v, ge_arena_t *a, ge_mail_t *out);

/* contributionDenied */
typedef struct {
    const char *contribution_frontend_link;
    const char *contribution_memo;
    const char *first_name;
    const char *last_name;
    const char *sender_alias;
} ge_contribution_denied_t;

int ge_render_contribution_denied(ge_locale_t locale, const ge_contribution_denied_t *v, ge_mail_t *out);
int ge_render_contribution_denied_into(ge_locale_t locale, const ge_contribution_denied_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_contribution_denied_into_fast(ge_locale_t locale, const ge_contribution_denied_t *v, ge_arena_t *a, ge_mail_t *out);

/* customEmail */
typedef struct {
    const char *community_url;
    const char *first_name;
    const char *last_name;
    const char *memo;
    const char *sender_alias;
    const char *sender_community_uuid;
    const char *sender_uuid;
    const char *subject;
} ge_custom_email_t;

int ge_render_custom_email(ge_locale_t locale, const ge_custom_email_t *v, ge_mail_t *out);
int ge_render_custom_email_into(ge_locale_t locale, const ge_custom_email_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_custom_email_into_fast(ge_locale_t locale, const ge_custom_email_t *v, ge_arena_t *a, ge_mail_t *out);

/* emailChangeConfirm */
typedef struct {
    const char *confirm_link;
    const char *first_name;
    const char *last_name;
    const char *valid_until;
} ge_email_change_confirm_t;

int ge_render_email_change_confirm(ge_locale_t locale, const ge_email_change_confirm_t *v, ge_mail_t *out);
int ge_render_email_change_confirm_into(ge_locale_t locale, const ge_email_change_confirm_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_email_change_confirm_into_fast(ge_locale_t locale, const ge_email_change_confirm_t *v, ge_arena_t *a, ge_mail_t *out);

/* emailChangeDone */
typedef struct {
    const char *first_name;
    const char *last_name;
    const char *new_email;
    const char *old_email;
    const char *support_email;
} ge_email_change_done_t;

int ge_render_email_change_done(ge_locale_t locale, const ge_email_change_done_t *v, ge_mail_t *out);
int ge_render_email_change_done_into(ge_locale_t locale, const ge_email_change_done_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_email_change_done_into_fast(ge_locale_t locale, const ge_email_change_done_t *v, ge_arena_t *a, ge_mail_t *out);

/* emailChangeNotice */
typedef struct {
    const char *first_name;
    const char *last_name;
    const char *new_email;
    const char *revoke_link;
    const char *valid_until;
} ge_email_change_notice_t;

int ge_render_email_change_notice(ge_locale_t locale, const ge_email_change_notice_t *v, ge_mail_t *out);
int ge_render_email_change_notice_into(ge_locale_t locale, const ge_email_change_notice_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_email_change_notice_into_fast(ge_locale_t locale, const ge_email_change_notice_t *v, ge_arena_t *a, ge_mail_t *out);

/* emailChangeSupport */
typedef struct {
    const char *alias;
    const char *first_name;
    const char *gdt_email;
    const char *last_name;
    const char *new_email;
    const char *old_email;
    bool typo_correction;
    bool take_back;
} ge_email_change_support_t;

int ge_render_email_change_support(ge_locale_t locale, const ge_email_change_support_t *v, ge_mail_t *out);
int ge_render_email_change_support_into(ge_locale_t locale, const ge_email_change_support_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_email_change_support_into_fast(ge_locale_t locale, const ge_email_change_support_t *v, ge_arena_t *a, ge_mail_t *out);

/* resetPassword */
typedef struct {
    const char *first_name;
    const char *hours;
    const char *last_name;
    const char *minutes;
    const char *resend_link;
    const char *reset_link;
} ge_reset_password_t;

int ge_render_reset_password(ge_locale_t locale, const ge_reset_password_t *v, ge_mail_t *out);
int ge_render_reset_password_into(ge_locale_t locale, const ge_reset_password_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_reset_password_into_fast(ge_locale_t locale, const ge_reset_password_t *v, ge_arena_t *a, ge_mail_t *out);

/* thankYouCardPaid */
typedef struct {
    const char *card_id;
    const char *card_label;
    const char *community_url;
    const char *first_name;
    const char *last_name;
    const char *recipient_community;
    const char *recipient_name;
    const char *transaction_amount;
    const char *transaction_memo;
} ge_thank_you_card_paid_t;

int ge_render_thank_you_card_paid(ge_locale_t locale, const ge_thank_you_card_paid_t *v, ge_mail_t *out);
int ge_render_thank_you_card_paid_into(ge_locale_t locale, const ge_thank_you_card_paid_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_thank_you_card_paid_into_fast(ge_locale_t locale, const ge_thank_you_card_paid_t *v, ge_arena_t *a, ge_mail_t *out);

/* transactionLinkRedeemed */
typedef struct {
    const char *community_url;
    const char *first_name;
    const char *last_name;
    const char *sender_alias;
    const char *sender_community;
    const char *transaction_amount;
    const char *transaction_memo;
} ge_transaction_link_redeemed_t;

int ge_render_transaction_link_redeemed(ge_locale_t locale, const ge_transaction_link_redeemed_t *v, ge_mail_t *out);
int ge_render_transaction_link_redeemed_into(ge_locale_t locale, const ge_transaction_link_redeemed_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_transaction_link_redeemed_into_fast(ge_locale_t locale, const ge_transaction_link_redeemed_t *v, ge_arena_t *a, ge_mail_t *out);

/* transactionReceived */
typedef struct {
    const char *community_url;
    const char *first_name;
    const char *last_name;
    const char *memo;
    const char *sender_alias;
    const char *sender_community_uuid;
    const char *sender_uuid;
    const char *transaction_amount;
} ge_transaction_received_t;

int ge_render_transaction_received(ge_locale_t locale, const ge_transaction_received_t *v, ge_mail_t *out);
int ge_render_transaction_received_into(ge_locale_t locale, const ge_transaction_received_t *v, ge_arena_t *a, ge_mail_t *out);
int ge_render_transaction_received_into_fast(ge_locale_t locale, const ge_transaction_received_t *v, ge_arena_t *a, ge_mail_t *out);

/* Introspection: enough to dispatch generically (a JSON API, say) without
 * writing code for each template. slot_names[0] is always "locale". */
typedef struct {
    const char         *name;
    uint32_t            prog_base;
    uint32_t            n_combos;
    uint32_t            n_slots;    /* including slot_names[0] == "locale" */
    const char *const  *slot_names;
    uint32_t            n_flags;
    const char *const  *flag_names;   /* NULL when the template has none */
    uint32_t            max_static_html;
    uint32_t            max_static_subject;
    uint32_t            max_slot_refs;
} ge_template_info_t;

extern const ge_template_info_t GE_TEMPLATES[17];

/* Largest static share across ALL templates, locales and variants. The slot
 * values are added at runtime: at most 6 output bytes per input byte
 * (" -> &quot;), counted per slot USE rather than per slot -- some values
 * appear twice in a document (a link as a button and as plain text). */
#define GE_MAX_STATIC_HTML     21962u
#define GE_MAX_STATIC_SUBJECT  119u
#define GE_MAX_SLOT_REFS       13u

/* Upper bound for one document if no input value is longer than max_field. */
#define GE_BUF_SIZE(max_field) \
    (GE_MAX_STATIC_HTML + GE_MAX_STATIC_SUBJECT + 2u + 6u * 2u * GE_MAX_SLOT_REFS * (max_field))

/* The generic counterpart to the typed wrappers: picks the variant from the
 * same values, addressed by slot index rather than by struct field. This is
 * what a dispatcher works with -- an HTTP handler, or a Node-API addon that
 * only ever sees a name and an object. */
uint32_t ge_combo_for(ge_template_t t, const char *const *slots, const bool *flags);

int ge_render_values(ge_template_t t, ge_locale_t locale, const char *const *slots,
                     const bool *flags, ge_mail_t *out);
int ge_render_values_into(ge_template_t t, ge_locale_t locale, const char *const *slots,
                          const bool *flags, ge_arena_t *a, ge_mail_t *out);
int ge_render_values_into_fast(ge_template_t t, ge_locale_t locale, const char *const *slots,
                               const bool *flags, ge_arena_t *a, ge_mail_t *out);

/* Renders without the generated if-logic: 'combo' picks the variant directly.
 * slots[0] is filled in by the renderer. */
int ge_render_by_index(ge_template_t t, ge_locale_t locale, uint32_t combo,
                       const char *const *slots, ge_mail_t *out);
int ge_render_by_index_into(ge_template_t t, ge_locale_t locale, uint32_t combo,
                            const char *const *slots, ge_arena_t *a, ge_mail_t *out);
int ge_render_by_index_into_fast(ge_template_t t, ge_locale_t locale, uint32_t combo,
                                 const char *const *slots, ge_arena_t *a, ge_mail_t *out);

/* Lookup by name, for the server's HTTP dispatch */
int          ge_template_by_name(const char *name);   /* -1 if unknown */
int          ge_locale_by_code(const char *code);     /* -1 if unknown */
const char  *ge_template_name(ge_template_t t);
const char  *ge_locale_code(ge_locale_t l);

/* Inline attachments (cid:) -- these live in the binary too */
extern const ge_asset_t GE_ASSETS[6];
#define GE_ASSET_COUNT 6

#endif
