import { createInterface } from 'node:readline/promises'
import {
  communityDescriptionSchema,
  communityNameSchema,
  communityUrlSchema,
  type HomeCommunitySetup,
} from '@gradido/shared/schemas'
import * as v from 'valibot'

/**
 * The first start against an empty database: ask the admin who this community is.
 *
 * Legacy reads `COMMUNITY_NAME` and `COMMUNITY_DESCRIPTION` out of the environment at every
 * start. gradido2 asks once and writes a row, because these are not settings — they are the
 * identity of a community, written once and then referred to. An environment variable that
 * has silently drifted from the row it created is a confusion that does not need to exist,
 * and the key pair that goes with the row could never have come from an env file anyway.
 *
 * **Only what a person knows is asked.** The uuid, the ed25519 key pair and the timestamps
 * are generated by the Interaction; a prompt for any of them would be a way to get them
 * wrong.
 *
 * Each answer is checked against the same schema an admin route will later check a rename
 * against, and a rejected answer is asked again rather than ending the setup — somebody is
 * standing at the terminal, and losing four correct answers because the fifth had a typo
 * would be gratuitous.
 */
export async function askForHomeCommunity(): Promise<HomeCommunitySetup> {
  const io = createInterface({ input: process.stdin, output: process.stdout })
  try {
    process.stdout.write(
      [
        '',
        'This database has no community yet.',
        '',
        'What follows is written once and becomes this instance’s identity: other',
        'communities will know it by these answers and by a key pair generated here.',
        '',
      ].join('\n'),
    )

    return {
      name: await ask(io, 'Community name', communityNameSchema),
      description: await ask(io, 'Description (optional)', communityDescriptionSchema),
      url: await ask(io, 'Public URL, e.g. https://gdd.example.org', communityUrlSchema),
    }
  } finally {
    io.close()
  }
}

/**
 * Whether anybody is there to be asked.
 *
 * Without a terminal there is nobody to answer, and a process that blocked on a prompt
 * nobody can see would look like a hung start rather than an unfinished setup. The caller
 * turns this into a message that says what to do instead.
 */
export function canAskForHomeCommunity(): boolean {
  return process.stdin.isTTY === true && process.stdout.isTTY === true
}

async function ask<TSchema extends v.GenericSchema<string, unknown>>(
  io: { question: (query: string) => Promise<string> },
  label: string,
  schema: TSchema,
): Promise<v.InferOutput<TSchema>> {
  for (;;) {
    const answer = v.safeParse(schema, await io.question(`${label}: `))
    if (answer.success) {
      return answer.output
    }
    /* The schema's own message, which is the one the admin frontend will show for the same
       field later. Written to stderr so a piped stdout stays clean. */
    process.stderr.write(`  ${answer.issues[0].message}\n`)
  }
}
