/**
 * `bun run publish` — everything the servers need out of `packages/`, in one place.
 *
 * Both implementations serve the same frontends, and neither of them can build one: a page is
 * vite's output, and the C path has no JavaScript in it at all. So the built pages are put
 * where both builds can find them — `publish/` at the repository root — and each embeds what
 * it finds there:
 *
 *   publish/sites.json    what the static web server serves, and where it is mounted
 *   publish/frontend/     the files of one site, exactly as they are handed out
 *   publish/admin/        the next one, once packages/admin exists
 *
 * At the root and not inside either implementation, because it belongs to neither. That it is
 * a directory a developer can list is half the point: what ends up inside a binary should be
 * something you can look at before it does, and a `du -sh publish/frontend` is the answer to
 * "why did the executable grow".
 *
 * It is generated, so it is not committed — `.gitignore` has it. Nothing may be edited here:
 * the next `bun run publish` clears it.
 *
 * The other half of what a server needs from `packages/` is not a page and does not land here:
 * `email-native`'s build writes the mail templates as C into `fast-servers/service-core`, and
 * `shared-native` builds the addon the TypeScript binary embeds. They are built here anyway,
 * because "prepare what the servers need" is one command or it is a list somebody forgets a
 * line of — see `fast-servers/AGENTS.md`, section 3c, for why that C is copied rather than
 * generated by the C build.
 *
 *   bun run publish                 build everything, then assemble publish/
 *   bun run publish --skip-build    assemble from what is already built
 *   API_BASE_URL=https://…          build the pages against another origin (see below)
 */
import { existsSync } from 'node:fs'
import { cp, mkdir, rm, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { run, turbo } from './run'

const ROOT = resolve(import.meta.dirname, '..')

/** Where the assembled sites go. Read by `scripts/bundle.ts` and by `fast-servers/build.zig`. */
export const PUBLISH = join(ROOT, 'publish')

export const MANIFEST = 'sites.json'

/**
 * The frontends, in the order a server should match them.
 *
 * `basePath` is both where the site is mounted and what it is built with: vite writes it into
 * every asset URL of `index.html`, so the two cannot be decided separately — which is why this
 * list is here, next to the build that uses it, and not in each bundler.
 */
const SITES = [
  {
    name: 'frontend',
    package: '@gradido/frontend',
    basePath: '',
    build: 'packages/frontend/build',
  },
  /* `packages/admin` does not exist yet. It is built exactly like the frontend — vite, the same
     `frontend-core`, its own `build/` — so it joins this list rather than needing anything new:

       { name: 'admin', package: '@gradido/admin', basePath: '/admin',
         build: 'packages/admin/build' },

     Both static servers already prefer the longer `basePath`, so `/admin/…` would go to the
     admin app and everything else to the frontend. */
] as const

/**
 * Packages that are built here without landing in `publish/`.
 *
 * `email-native` writes the mail templates as C into `fast-servers/service-core/{include,src}/
 * email/` — that is what makes both implementations send the same bytes, and it happens in
 * that package's build script rather than in the C build, which stays free of node.
 * `shared-native` is the addon the TypeScript binary embeds; the C path links the same
 * determinism-critical code as a library instead.
 */
const SERVER_PACKAGES = ['@gradido/email-native', '@gradido/shared-native'] as const

/**
 * One file of one site, and everything a server has to know to hand it out.
 *
 * The type and the ETag are decided **here**, once, rather than by each server: two static
 * servers that inferred a content type from an extension separately would disagree about one
 * of them eventually, and two that hashed the bytes separately would disagree about all of
 * them. What a client gets must not depend on which implementation is deployed — that is the
 * rule `sc_http_reason` follows between the two C backends, applied between the two
 * implementations.
 */
export type PublishedFile = {
  /** Path below the site's directory, `/` separated: `assets/index-Ca4jjj45.js`. */
  readonly path: string
  /** The `Content-Type` header, complete with charset where one belongs. */
  readonly type: string
  /** The ETag, without the quotes a server puts around it on the wire. */
  readonly etag: string
  /** Whether the name carries a content hash, and the file may therefore be cached for a year. */
  readonly immutable: boolean
}

/** One site, as `publish/sites.json` describes it. */
export type PublishedSite = {
  readonly name: string
  /** Where the site is mounted: `''` for the domain root, `/admin` for a sub-path. */
  readonly basePath: string
  /** The site's directory below `publish/`. */
  readonly dir: string
  /** The entry document, served for every path the site has no file for. */
  readonly index: string
  /** Every file, sorted by path. */
  readonly files: readonly PublishedFile[]
  readonly bytes: number
}

export type Manifest = {
  readonly sites: readonly PublishedSite[]
}

export type PublishOptions = {
  /** Assemble from what is already built, rather than building first. */
  readonly skipBuild?: boolean
}

export async function publish(options: PublishOptions = {}): Promise<Manifest> {
  if (!options.skipBuild) {
    await build()
  }

  /* Cleared rather than written over: a file that a build stopped producing has to stop being
     served, and the only way a copy notices that is by not being there. */
  await rm(PUBLISH, { recursive: true, force: true })
  await mkdir(PUBLISH, { recursive: true })

  const sites: PublishedSite[] = []
  for (const site of SITES) {
    const source = join(ROOT, site.build)
    if (!existsSync(source)) {
      throw new Error(
        `${site.package} produced no ${site.build}` +
          (options.skipBuild ? ' — --skip-build was passed and it was never built' : ''),
      )
    }
    await cp(source, join(PUBLISH, site.name), { recursive: true })
    sites.push(await describe(site.name, site.basePath))
  }

  const manifest: Manifest = { sites }
  await writeFile(join(PUBLISH, MANIFEST), `${JSON.stringify(manifest, null, 2)}\n`)

  for (const site of sites) {
    console.log(
      `publish: ${site.name} → publish/${site.dir}` +
        ` (${site.files.length} files, ${(site.bytes / 1024).toFixed(0)} kB` +
        `${site.basePath === '' ? '' : `, mounted at ${site.basePath}`})`,
    )
  }
  return manifest
}

/**
 * Builds the pages, and the two packages whose output a server needs elsewhere.
 *
 * One turbo run per site, because each is built with its own `BASE_PATH` and turbo takes one
 * environment per run. The rest go in a single run afterwards.
 */
async function build(): Promise<void> {
  for (const site of SITES) {
    await turbo(['build', `--filter=${site.package}`], {
      /* Empty unless a deployment says otherwise: the page is served by the server it calls,
         whichever implementation that is — see `packages/frontend/src/config/schema.ts`.
         `process.env` wins over the `.env` vite loads, so a development `.env` in the package
         cannot leak a localhost URL into a release. */
      API_BASE_URL: process.env.API_BASE_URL ?? '',
      BASE_PATH: site.basePath,
    })
  }
  await turbo(['build', ...SERVER_PACKAGES.map((name) => `--filter=${name}`)], {})
}

/**
 * What a file's extension means on the wire.
 *
 * An unknown extension stops the publish rather than defaulting to `application/octet-stream`:
 * a stylesheet or a script served under that type is ignored by the browser, and the page then
 * fails in a way that looks like anything but a missing line in this table.
 */
const CONTENT_TYPES: Record<string, string> = {
  '.avif': 'image/avif',
  '.css': 'text/css; charset=utf-8',
  '.gif': 'image/gif',
  '.htm': 'text/html; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.ico': 'image/x-icon',
  '.jpeg': 'image/jpeg',
  '.jpg': 'image/jpeg',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.ttf': 'font/ttf',
  '.txt': 'text/plain; charset=utf-8',
  '.wasm': 'application/wasm',
  '.webmanifest': 'application/manifest+json',
  '.webp': 'image/webp',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
}

/**
 * Vite writes content-hashed names into this directory and nowhere else, which is what makes a
 * year-long cache safe: the name changes when the bytes do. Everything outside it —
 * `index.html`, `img/`, `locales/` — keeps its name across builds and is revalidated instead.
 */
const HASHED_DIRECTORY = 'assets/'

/** Walks one assembled site and writes down what is in it. */
async function describe(name: string, basePath: string): Promise<PublishedSite> {
  const directory = join(PUBLISH, name)
  const glob = new Bun.Glob('**/*')
  const files: PublishedFile[] = []
  let bytes = 0

  for await (const file of glob.scan({ cwd: directory, onlyFiles: true })) {
    /* Bun.Glob yields the platform separator on Windows; a URL path uses the other one, and so
       does every reader of this manifest. */
    const path = file.split(/[\\/]/u).join('/')
    const extension = path.slice(path.lastIndexOf('.')).toLowerCase()
    const type = CONTENT_TYPES[extension]
    if (type === undefined) {
      throw new Error(
        `publish/${name}/${path}: nothing in scripts/publish.ts says what "${extension}" is.` +
          ' Add it to CONTENT_TYPES.',
      )
    }
    const content = await Bun.file(join(directory, file)).bytes()
    files.push({
      path,
      type,
      /* Not a cryptographic hash and not meant to be: an ETag says "the same bytes as last
         time" to a cache, and nothing downstream trusts it with anything else. */
      etag: Bun.hash(content).toString(16),
      immutable: path.startsWith(HASHED_DIRECTORY),
    })
    bytes += content.length
  }
  files.sort((left, right) => (left.path < right.path ? -1 : left.path > right.path ? 1 : 0))

  if (!files.some((file) => file.path === 'index.html')) {
    throw new Error(`publish/${name}/index.html is missing — that site has no app to serve`)
  }
  return { name, basePath, dir: name, index: 'index.html', files, bytes }
}

/** Reads what a previous run wrote. Both bundlers go through this rather than walking the tree. */
export async function readManifest(): Promise<Manifest> {
  const path = join(PUBLISH, MANIFEST)
  if (!existsSync(path)) {
    throw new Error(`publish/${MANIFEST} is missing — run \`bun run publish\` first`)
  }
  return (await Bun.file(path).json()) as Manifest
}

function usage(): string {
  return `bun run publish — build the frontends and assemble publish/

  --skip-build      assemble from what is already built
  -h, --help        this text

The pages are built for the server that serves them: API_BASE_URL empty, BASE_PATH set to
where each site is mounted. Set API_BASE_URL in the environment to override the first.`
}

if (import.meta.main) {
  const argv = process.argv.slice(2)
  if (argv.includes('-h') || argv.includes('--help')) {
    console.log(usage())
  } else {
    const unknown = argv.filter((argument) => argument !== '--skip-build')
    if (unknown.length !== 0) {
      console.error(`unknown option "${unknown[0]}"\n\n${usage()}`)
      process.exit(1)
    }
    await publish({ skipBuild: argv.includes('--skip-build') })
  }
}
