/**
 * Makes `@chainsafe/libp2p-quic` survive `bun build --compile`.
 *
 * Its loader (dist/src/napi.js, generated by NAPI-RS) picks the native binding at run time with
 * `createRequire(import.meta.url)` and a platform switch. The bundler cannot follow that, so the
 * `.node` file never enters the binary and the dht-node role starts without QUIC -- "Cannot find
 * native binding". This replaces the loader, at build time, with a static require of the binding
 * for the platform being built, which is what `--compile` embeds. First written and tested in
 * libp2p-ffi, interop/js/quic-binding-plugin.ts.
 *
 * The binding is an optional dependency of the QUIC package and is resolved from there: bun
 * installs workspaces isolated, so from this directory it would not be found.
 */
import { readdirSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import type { BunPlugin } from 'bun'

const EXPORTS = [
  'Client',
  'Connection',
  'ConnectionStats',
  'EndpointStats',
  'QuinnConfig',
  'Server',
  'Stream',
  'SocketFamily',
]

function bindingPackage(): string {
  const { platform, arch } = process
  if (platform === 'linux') {
    // glibc unless the runtime says otherwise; a musl binary is built on a musl host.
    const report = process.report?.getReport() as { header?: { glibcVersionRuntime?: string } }
    return `@chainsafe/libp2p-quic-linux-${arch}-${report?.header?.glibcVersionRuntime !== undefined ? 'gnu' : 'musl'}`
  }
  if (platform === 'darwin') {
    return `@chainsafe/libp2p-quic-darwin-${arch}`
  }
  if (platform === 'win32') {
    return `@chainsafe/libp2p-quic-win32-${arch}-msvc`
  }
  throw new Error(`no libp2p-quic binding for ${platform}-${arch}`)
}

/** @p from is a package.json that depends on @chainsafe/libp2p-quic. */
export function quicBinding(from: string): BunPlugin {
  return {
    name: 'libp2p-quic static binding',
    setup(build) {
      build.onLoad({ filter: /@chainsafe[\\/]libp2p-quic[\\/]dist[\\/]src[\\/]napi\.js$/ }, () => {
        const quic = createRequire(from).resolve('@chainsafe/libp2p-quic/package.json')
        const binding = dirname(createRequire(quic).resolve(`${bindingPackage()}/package.json`))
        const file = readdirSync(binding).find((name) => name.endsWith('.node'))
        if (file === undefined) {
          throw new Error(`${binding} has no .node file`)
        }
        return {
          loader: 'js',
          contents: `const binding = require(${JSON.stringify(join(binding, file))})\nexport const { ${EXPORTS.join(', ')} } = binding\n`,
        }
      })
    },
  }
}
